import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
/**
 * 創建側邊欄使您能夠：
 - 創建文檔的有序分組
 - 為該組中的每個文檔渲染側邊欄
 - 提供上一頁/下一頁導航功能

 側邊欄可以從文件系統自動生成，或在此處明確定義。

 您可以根據需要創建任意數量的側邊欄。
 */
const sidebars: SidebarsConfig = {
	// 預設情況下，Docusaurus 會根據 docs 資料夾結構生成側邊欄
	tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

	// 但您也可以手動創建側邊欄
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
